/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libsodiumjni_internal_SodiumApi */

#ifndef _Included_libsodiumjni_internal_SodiumApi
#define _Included_libsodiumjni_internal_SodiumApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libsodiumjni_internal_SodiumApi
 * Method:    sodium_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_libsodiumjni_internal_SodiumApi_sodium_1init
  (JNIEnv *, jobject);

/*
 * Class:     libsodiumjni_internal_SodiumApi
 * Method:    crypto_box_seal
 * Signature: ([B[BJ[B)I
 */
JNIEXPORT jint JNICALL Java_libsodiumjni_internal_SodiumApi_crypto_1box_1seal
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
